// Mocks generated by Mockito 5.4.5 from annotations
// in hive_project/test/module/domain/repositories/repositories_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:hive_project/module/domain/entities/food/food_entities.dart'
    as _i2;
import 'package:hive_project/module/domain/entities/ingredients/ingredients_entity.dart'
    as _i4;
import 'package:hive_project/module/domain/entities/ingredients_items/ingredient_items_entity.dart'
    as _i7;
import 'package:hive_project/module/domain/entities/intermediate_items/intermediate_items_entity.dart'
    as _i9;
import 'package:hive_project/module/domain/entities/report/credit_report_etities.dart'
    as _i12;
import 'package:hive_project/module/domain/entities/report/debit_report_entities.dart'
    as _i14;
import 'package:hive_project/module/domain/repositories/food_prep_repo.dart'
    as _i10;
import 'package:hive_project/module/domain/repositories/ingredients_items_repo.dart'
    as _i6;
import 'package:hive_project/module/domain/repositories/ingredients_repo.dart'
    as _i3;
import 'package:hive_project/module/domain/repositories/intermediate_items_repo.dart'
    as _i8;
import 'package:hive_project/module/domain/repositories/report/credit_report_repo.dart'
    as _i11;
import 'package:hive_project/module/domain/repositories/report/debit_report_repo.dart'
    as _i13;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOtherRequiredFoodEntities_0 extends _i1.SmartFake
    implements _i2.OtherRequiredFoodEntities {
  _FakeOtherRequiredFoodEntities_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IngredientsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientsRepo extends _i1.Mock implements _i3.IngredientsRepo {
  MockIngredientsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.IngredientsEntity> getIngredients() => (super.noSuchMethod(
        Invocation.method(
          #getIngredients,
          [],
        ),
        returnValue: <_i4.IngredientsEntity>[],
      ) as List<_i4.IngredientsEntity>);

  @override
  _i5.Future<void> addIngredient(String? name) => (super.noSuchMethod(
        Invocation.method(
          #addIngredient,
          [name],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [IngredientsItemsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientsItemsRepo extends _i1.Mock
    implements _i6.IngredientsItemsRepo {
  MockIngredientsItemsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.IngredientItemsEntity> getIngredientsItems() => (super.noSuchMethod(
        Invocation.method(
          #getIngredientsItems,
          [],
        ),
        returnValue: <_i7.IngredientItemsEntity>[],
      ) as List<_i7.IngredientItemsEntity>);

  @override
  _i5.Future<void> addIngredientItems(
    String? ingredientname,
    int? ingredientModels,
    double? ingredientPrice,
    int? materialsUnit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIngredientItems,
          [
            ingredientname,
            ingredientModels,
            ingredientPrice,
            materialsUnit,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void updateIngredientItem(
    String? ingredientName,
    int? newMaterialsUnit,
    double? newPrice,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateIngredientItem,
          [
            ingredientName,
            newMaterialsUnit,
            newPrice,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IntermediateItemsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntermediateItemsRepo extends _i1.Mock
    implements _i8.IntermediateItemsRepo {
  MockIntermediateItemsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i9.IntermediateItemsEntity> getIntermediateItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getIntermediateItems,
          [],
        ),
        returnValue: <_i9.IntermediateItemsEntity>[],
      ) as List<_i9.IntermediateItemsEntity>);

  @override
  _i5.Future<void> addIntermediateItem(
    String? intermediateItemName,
    int? ingredientsItemModels,
    int? availableQuantity,
    int? requiredQuantity,
    int? servingQuantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIntermediateItem,
          [
            intermediateItemName,
            ingredientsItemModels,
            availableQuantity,
            requiredQuantity,
            servingQuantity,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void updateIntermediateItem(
    String? intermediateItemName,
    int? newServingQuantity,
    int? newRequiredQuantity,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateIntermediateItem,
          [
            intermediateItemName,
            newServingQuantity,
            newRequiredQuantity,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FoodPrepRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodPrepRepo extends _i1.Mock implements _i10.FoodPrepRepo {
  MockFoodPrepRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.FoodEntities> getFoodPrepItems() => (super.noSuchMethod(
        Invocation.method(
          #getFoodPrepItems,
          [],
        ),
        returnValue: <_i2.FoodEntities>[],
      ) as List<_i2.FoodEntities>);

  @override
  _i5.Future<void> addFoodPrepItems(
    String? foodPrepName,
    int? intermediateItemsModels,
    List<dynamic>? otherRequiredFoodEntities,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFoodPrepItems,
          [
            foodPrepName,
            intermediateItemsModels,
            otherRequiredFoodEntities,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.OtherRequiredFoodEntities> getOtherRequiredFoodItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOtherRequiredFoodItems,
          [],
        ),
        returnValue: _i5.Future<_i2.OtherRequiredFoodEntities>.value(
            _FakeOtherRequiredFoodEntities_0(
          this,
          Invocation.method(
            #getOtherRequiredFoodItems,
            [],
          ),
        )),
      ) as _i5.Future<_i2.OtherRequiredFoodEntities>);

  @override
  _i5.Future<void> addOtherRequiredFoodItems(
    String? itemName,
    double? quantity,
    double? price,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOtherRequiredFoodItems,
          [
            itemName,
            quantity,
            price,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [CreditReportRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreditReportRepo extends _i1.Mock implements _i11.CreditReportRepo {
  MockCreditReportRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.CreditEntities> getCreditReportItems() => (super.noSuchMethod(
        Invocation.method(
          #getCreditReportItems,
          [],
        ),
        returnValue: <_i12.CreditEntities>[],
      ) as List<_i12.CreditEntities>);

  @override
  _i5.Future<void> addCreditReportItems(
    String? ingredient,
    double? price,
    double? materialUnit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCreditReportItems,
          [
            ingredient,
            price,
            materialUnit,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DebitReportRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockDebitReportRepo extends _i1.Mock implements _i13.DebitReportRepo {
  MockDebitReportRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i14.DebitReportEntities> getDebitReportItems() => (super.noSuchMethod(
        Invocation.method(
          #getDebitReportItems,
          [],
        ),
        returnValue: <_i14.DebitReportEntities>[],
      ) as List<_i14.DebitReportEntities>);

  @override
  _i5.Future<void> addDebitReportItems(
    String? foodName,
    int? servingQuantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDebitReportItems,
          [
            foodName,
            servingQuantity,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
