// Mocks generated by Mockito 5.4.5 from annotations
// in hive_project/test/module/data/repositories/repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:hive_project/module/data/datasources/food_prep_data_source.dart'
    as _i5;
import 'package:hive_project/module/data/datasources/ingredients_data_source.dart'
    as _i2;
import 'package:hive_project/module/data/datasources/ingredients_items_data_source.dart'
    as _i3;
import 'package:hive_project/module/data/datasources/intermediate_items_data_source.dart'
    as _i4;
import 'package:hive_project/module/data/datasources/report/credit_report_data_source.dart'
    as _i7;
import 'package:hive_project/module/data/datasources/report/debit_report_data_source.dart'
    as _i8;
import 'package:hive_project/module/data/repositories/food_prep_repo_impl.dart'
    as _i16;
import 'package:hive_project/module/data/repositories/ingredients_items_repo_impl.dart'
    as _i12;
import 'package:hive_project/module/data/repositories/ingredients_repo_impl.dart'
    as _i9;
import 'package:hive_project/module/data/repositories/intermediate_items_repo_impl.dart'
    as _i14;
import 'package:hive_project/module/data/repositories/report/credit_report_repo_impl.dart'
    as _i17;
import 'package:hive_project/module/data/repositories/report/debit_report_repo_impl.dart'
    as _i19;
import 'package:hive_project/module/domain/entities/food/food_entities.dart'
    as _i6;
import 'package:hive_project/module/domain/entities/ingredients/ingredients_entity.dart'
    as _i10;
import 'package:hive_project/module/domain/entities/ingredients_items/ingredient_items_entity.dart'
    as _i13;
import 'package:hive_project/module/domain/entities/intermediate_items/intermediate_items_entity.dart'
    as _i15;
import 'package:hive_project/module/domain/entities/report/credit_report_etities.dart'
    as _i18;
import 'package:hive_project/module/domain/entities/report/debit_report_entities.dart'
    as _i20;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIngredientsDataSource_0 extends _i1.SmartFake
    implements _i2.IngredientsDataSource {
  _FakeIngredientsDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIngredientsItemsDataSource_1 extends _i1.SmartFake
    implements _i3.IngredientsItemsDataSource {
  _FakeIngredientsItemsDataSource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIntermediateItemsDataSource_2 extends _i1.SmartFake
    implements _i4.IntermediateItemsDataSource {
  _FakeIntermediateItemsDataSource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFoodPrepDataSource_3 extends _i1.SmartFake
    implements _i5.FoodPrepDataSource {
  _FakeFoodPrepDataSource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOtherRequiredFoodEntities_4 extends _i1.SmartFake
    implements _i6.OtherRequiredFoodEntities {
  _FakeOtherRequiredFoodEntities_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreditReportDataSource_5 extends _i1.SmartFake
    implements _i7.CreditReportDataSource {
  _FakeCreditReportDataSource_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDebitReportDataSource_6 extends _i1.SmartFake
    implements _i8.DebitReportDataSource {
  _FakeDebitReportDataSource_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IngredientsRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientsRepoImpl extends _i1.Mock
    implements _i9.IngredientsRepoImpl {
  MockIngredientsRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IngredientsDataSource get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _FakeIngredientsDataSource_0(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as _i2.IngredientsDataSource);

  @override
  List<_i10.IngredientsEntity> getIngredients() => (super.noSuchMethod(
        Invocation.method(
          #getIngredients,
          [],
        ),
        returnValue: <_i10.IngredientsEntity>[],
      ) as List<_i10.IngredientsEntity>);

  @override
  _i11.Future<void> addIngredient(String? name) => (super.noSuchMethod(
        Invocation.method(
          #addIngredient,
          [name],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);
}

/// A class which mocks [IngredientsItemsRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockIngredientsItemsRepoImpl extends _i1.Mock
    implements _i12.IngredientsItemsRepoImpl {
  MockIngredientsItemsRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.IngredientsItemsDataSource get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _FakeIngredientsItemsDataSource_1(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as _i3.IngredientsItemsDataSource);

  @override
  List<_i13.IngredientItemsEntity> getIngredientsItems() => (super.noSuchMethod(
        Invocation.method(
          #getIngredientsItems,
          [],
        ),
        returnValue: <_i13.IngredientItemsEntity>[],
      ) as List<_i13.IngredientItemsEntity>);

  @override
  _i11.Future<void> addIngredientItems(
    String? ingredientname,
    int? ingredientModels,
    double? ingredientPrice,
    int? materialsUnit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIngredientItems,
          [
            ingredientname,
            ingredientModels,
            ingredientPrice,
            materialsUnit,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void updateIngredientItem(
    String? ingredientName,
    int? newMaterialsUnit,
    double? newPrice,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateIngredientItem,
          [
            ingredientName,
            newMaterialsUnit,
            newPrice,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IntermediateItemsRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntermediateItemsRepoImpl extends _i1.Mock
    implements _i14.IntermediateItemsRepoImpl {
  MockIntermediateItemsRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.IntermediateItemsDataSource get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _FakeIntermediateItemsDataSource_2(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as _i4.IntermediateItemsDataSource);

  @override
  List<_i15.IntermediateItemsEntity> getIntermediateItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getIntermediateItems,
          [],
        ),
        returnValue: <_i15.IntermediateItemsEntity>[],
      ) as List<_i15.IntermediateItemsEntity>);

  @override
  _i11.Future<void> addIntermediateItem(
    String? intermediateItemName,
    int? ingredientsItemModels,
    int? availableQuantity,
    int? requiredQuantity,
    int? servingQuantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIntermediateItem,
          [
            intermediateItemName,
            ingredientsItemModels,
            availableQuantity,
            requiredQuantity,
            servingQuantity,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void updateIntermediateItem(
    String? intermediateItemName,
    int? newServingQuantity,
    int? newRequiredQuantity,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateIntermediateItem,
          [
            intermediateItemName,
            newServingQuantity,
            newRequiredQuantity,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FoodPrepRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodPrepRepoImpl extends _i1.Mock implements _i16.FoodPrepRepoImpl {
  MockFoodPrepRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.FoodPrepDataSource get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _FakeFoodPrepDataSource_3(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as _i5.FoodPrepDataSource);

  @override
  List<_i6.FoodEntities> getFoodPrepItems() => (super.noSuchMethod(
        Invocation.method(
          #getFoodPrepItems,
          [],
        ),
        returnValue: <_i6.FoodEntities>[],
      ) as List<_i6.FoodEntities>);

  @override
  _i11.Future<void> addFoodPrepItems(
    String? foodPrepName,
    int? intermediateItemsModels,
    List<dynamic>? otherRequiredFoodEntities,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFoodPrepItems,
          [
            foodPrepName,
            intermediateItemsModels,
            otherRequiredFoodEntities,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> addOtherRequiredFoodItems(
    String? itemName,
    double? quantity,
    double? price,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOtherRequiredFoodItems,
          [
            itemName,
            quantity,
            price,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i6.OtherRequiredFoodEntities> getOtherRequiredFoodItems() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOtherRequiredFoodItems,
          [],
        ),
        returnValue: _i11.Future<_i6.OtherRequiredFoodEntities>.value(
            _FakeOtherRequiredFoodEntities_4(
          this,
          Invocation.method(
            #getOtherRequiredFoodItems,
            [],
          ),
        )),
      ) as _i11.Future<_i6.OtherRequiredFoodEntities>);
}

/// A class which mocks [CreditReportRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreditReportRepoImpl extends _i1.Mock
    implements _i17.CreditReportRepoImpl {
  MockCreditReportRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CreditReportDataSource get creditReportDataSource => (super.noSuchMethod(
        Invocation.getter(#creditReportDataSource),
        returnValue: _FakeCreditReportDataSource_5(
          this,
          Invocation.getter(#creditReportDataSource),
        ),
      ) as _i7.CreditReportDataSource);

  @override
  _i11.Future<void> addCreditReportItems(
    String? ingredient,
    double? price,
    double? materialUnit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCreditReportItems,
          [
            ingredient,
            price,
            materialUnit,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i18.CreditEntities> getCreditReportItems() => (super.noSuchMethod(
        Invocation.method(
          #getCreditReportItems,
          [],
        ),
        returnValue: <_i18.CreditEntities>[],
      ) as List<_i18.CreditEntities>);
}

/// A class which mocks [DebitReportRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockDebitReportRepoImpl extends _i1.Mock
    implements _i19.DebitReportRepoImpl {
  MockDebitReportRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.DebitReportDataSource get debitReportDataSource => (super.noSuchMethod(
        Invocation.getter(#debitReportDataSource),
        returnValue: _FakeDebitReportDataSource_6(
          this,
          Invocation.getter(#debitReportDataSource),
        ),
      ) as _i8.DebitReportDataSource);

  @override
  _i11.Future<void> addDebitReportItems(
    String? foodName,
    int? servingQuantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addDebitReportItems,
          [
            foodName,
            servingQuantity,
          ],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i20.DebitReportEntities> getDebitReportItems() => (super.noSuchMethod(
        Invocation.method(
          #getDebitReportItems,
          [],
        ),
        returnValue: <_i20.DebitReportEntities>[],
      ) as List<_i20.DebitReportEntities>);
}
